=== elaa0505/jitl/jitl-jobs/src/test/resources/jobchain_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Andreas Pueschel (APL Software GmbH) -->
<!--W3C Schema generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="div">
		<xs:complexType/>
	</xs:element>
	<xs:element name="job_chain">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="note" maxOccurs="unbounded"/>
				<xs:element ref="order"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="note">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="div" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="language" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="order">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params"/>
				<xs:element ref="process"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="param">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="params">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="param"/>
				<xs:element ref="note"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="process">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="note" maxOccurs="unbounded"/>
				<xs:element ref="params"/>
			</xs:sequence>
			<xs:attribute name="state" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="job_chain"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== elaa0505/jitl/jitl-jobs/src/test/resources/com/sos/jitl/JobchainNodeSubstitute/job_chain.config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Andreas Pueschel (APL Software GmbH) -->
<?xml-stylesheet type="text/xsl" href="scheduler_configuration_documentation.xsl"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\development\products\jitl\jitl-jobs\src\test\resources\com\sos\jitl\configurationmonitor\jobchain_config.xsd">
	<job_chain name="create_sos_simulation222">
		<order>
			<params>
				<param name="global_param_1" value="global_param_1_val3"/>
				<param name="global_param_2" value="global_param_2_val4"/>
			</params>
			<process state="x100">
				<params>
					<param name="node_param_1" value="node_param_1_val1"/>
					<param name="node_param_2" value="node_param_2_${global_param_1}_val2"/>
				</params>
			</process>
			<process state="x200">
				<params>
					<param name="node_param_3" value="node_param_3_val1"/>
					<param name="node_param_4" value="node_param_4_val2"/>
				</params>
			</process>
		</order>
	</job_chain>
</settings>
