=== elaa0505/jitl/jitl-jobs/src/test/java/com/sos/jitl/agentbatchinstaller/jobscheduler_universal_agent_batch_install/batch_install/scheduler_universal_agent_installations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Andreas Pueschel (APL Software GmbH) -->
<!--W3C Schema generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="agent_options">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="java_home" minOccurs="0"/>
				<xs:element ref="java_options" minOccurs="0"/>
				<xs:element ref="scheduler_http_port" minOccurs="0"/>
				<xs:element ref="scheduler_ip_address" minOccurs="0"/>
				<xs:element ref="scheduler_user" minOccurs="0"/>
				<xs:element ref="scheduler_log_dir" minOccurs="0"/>
				<xs:element ref="scheduler_kill_script" minOccurs="0"/>
				<xs:element ref="scheduler_pid_file_dir" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="settings" type="xs:string"/>
	<xs:element name="profile" type="xs:string"/>
	<xs:element name="auth_file" type="xs:string"/>
	<xs:element name="auth_method" type="xs:string"/>
	<xs:element name="command" type="xs:string"/>
	<xs:element name="file_spec" type="xs:string"/>
	<xs:element name="globals">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="install_path" minOccurs="0"/>
				<xs:element ref="transfer" minOccurs="0"/>
				<xs:element ref="ssh" minOccurs="0"/>
				<xs:element ref="postprocessing" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="install_path" type="xs:string"/>
	<xs:element name="installation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="install_path" minOccurs="0"/>
				<xs:element ref="agent_options" minOccurs="0"/>
				<xs:element ref="transfer" minOccurs="0"/>
				<xs:element ref="ssh" minOccurs="0"/>
				<xs:element ref="postprocessing" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="lastRun" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="installations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="globals"/>
				<xs:element ref="installation" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="lastRun" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="java_home" type="xs:string"/>
	<xs:element name="java_options" type="xs:string"/>
	<xs:element name="operation" type="xs:string"/>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="port" type="xs:string"/>
	<xs:element name="protocol" type="xs:string"/>
	<xs:element name="dir" type="xs:string"/>
	<xs:element name="scheduler_http_port" type="xs:int"/>
	<xs:element name="scheduler_ip_address" type="xs:string"/>
	<xs:element name="scheduler_kill_script" type="xs:string"/>
	<xs:element name="scheduler_log_dir" type="xs:string"/>
	<xs:element name="scheduler_pid_file_dir" type="xs:string"/>
	<xs:element name="scheduler_user" type="xs:string"/>
	<xs:element name="source">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="host" minOccurs="0"/>
				<xs:element ref="port" minOccurs="0"/>
				<xs:element ref="protocol" minOccurs="0"/>
				<xs:element ref="user" minOccurs="0"/>
				<xs:element ref="password" minOccurs="0"/>
				<xs:element ref="dir" minOccurs="0"/>
				<xs:element ref="ssh_auth_method" minOccurs="0"/>
				<xs:element ref="ssh_auth_file" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ssh">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user" minOccurs="0"/>
				<xs:element ref="password" minOccurs="0"/>
				<xs:element ref="sudo_password" minOccurs="0"/>
				<xs:element ref="auth_method" minOccurs="0"/>
				<xs:element ref="auth_file" minOccurs="0"/>
				<xs:element ref="host" minOccurs="0"/>
				<xs:element ref="port" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ssh_auth_file" type="xs:string"/>
	<xs:element name="ssh_auth_method" type="xs:string"/>
	<xs:element name="sudo_password" type="xs:string"/>
	<xs:element name="target">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="host" minOccurs="0"/>
				<xs:element ref="port" minOccurs="0"/>
				<xs:element ref="protocol" minOccurs="0"/>
				<xs:element ref="user" minOccurs="0"/>
				<xs:element ref="password" minOccurs="0"/>
				<xs:element ref="dir" minOccurs="0"/>
				<xs:element ref="ssh_auth_method" minOccurs="0"/>
				<xs:element ref="ssh_auth_file" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="transfer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings" minOccurs="0"/>
				<xs:element ref="profile" minOccurs="0"/>
				<xs:element ref="operation" minOccurs="0"/>
				<xs:element ref="file_spec" minOccurs="0"/>
				<xs:element ref="source" minOccurs="0"/>
				<xs:element ref="target" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="user" type="xs:string"/>
	<xs:element name="postprocessing">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== elaa0505/jitl/jitl-jobs/src/test/java/com/sos/jitl/agentbatchinstaller/scheduler_universal_agent_installations.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<installations lastRun="2011-03-04 15:03" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\development_110\products\jitl\jitl-jobs\src\test\java\com\sos\jitl\agentbatchinstaller\scheduler_universal_agent_installations.xsd">
	<globals>
		<install_path>/opt/sos-berlin.com/jobscheduler</install_path>
		<transfer>
			<operation>copy</operation>
			<file_spec>.*</file_spec>
			<source>
				<host>host</host>
				<port>x22</port>
				<protocol>protocol</protocol>
				<user>user</user>
				<password>password</password>
				<dir>batch_install</dir>
				<ssh_auth_method>ssh_auth_method</ssh_auth_method>
				<ssh_auth_file>ssh_auth_file</ssh_auth_file>
			</source>
			<target>
				<host>host</host>
				<port>x22</port>
				<protocol>protocol</protocol>
				<user>user</user>
				<password>password</password>
				<dir>batch_install</dir>
				<ssh_auth_method>ssh_auth_method</ssh_auth_method>
				<ssh_auth_file>ssh_auth_file</ssh_auth_file>
			</target>
		</transfer>
		<ssh>
			<auth_method>password</auth_method>
			<port>x22</port>
		</ssh>
	</globals>
	<installation lastRun="2011-03-04 15:03">
		<host>sampleHost</host>
		<install_path>/opt/sos-berlin.com/jobscheduler</install_path>
		<agent_options>
			<java_home>java home</java_home>
			<java_options>java options</java_options>
			<scheduler_http_port>4445</scheduler_http_port>
			<scheduler_ip_address>127.0.0.1</scheduler_ip_address>
			<scheduler_user>scheduler user</scheduler_user>
			<scheduler_log_dir>scheduler log dir</scheduler_log_dir>
			<scheduler_kill_script>scheduler kill script</scheduler_kill_script>
			<scheduler_pid_file_dir>scheduler pid file dir</scheduler_pid_file_dir>
		</agent_options>
		<transfer>
			<operation>copy</operation>
			<file_spec>.*</file_spec>
			<source>
				<host>host</host>
				<port>x22</port>
				<protocol>protocol</protocol>
				<user>user</user>
				<password>password</password>
				<dir>batch_install</dir>
				<ssh_auth_method>ssh_auth_method</ssh_auth_method>
				<ssh_auth_file>ssh_auth_file</ssh_auth_file>
			</source>
			<target>
				<host>host</host>
				<port>x22</port>
				<protocol>protocol</protocol>
				<user>user</user>
				<password>password</password>
				<dir>batch_install</dir>
				<ssh_auth_method>ssh_auth_method</ssh_auth_method>
				<ssh_auth_file>ssh_auth_file</ssh_auth_file>
			</target>
		</transfer>
		<ssh>
			<user>test</user>
			<password>myPwd</password>
			<sudo_password>mySudoPwd</sudo_password>
			<auth_method>password</auth_method>
			<port>22</port>
		</ssh>
	</installation>
	<installation lastRun="2011-03-04 15:03">
		<host>sampleHost</host>
		<install_path>/opt/sos-berlin.com/jobscheduler</install_path>
		<agent_options>
			<java_home>java home</java_home>
			<java_options>java options</java_options>
			<scheduler_http_port>4445</scheduler_http_port>
			<scheduler_ip_address>127.0.0.1</scheduler_ip_address>
			<scheduler_user>scheduler user</scheduler_user>
			<scheduler_log_dir>scheduler log dir</scheduler_log_dir>
			<scheduler_kill_script>scheduler kill script</scheduler_kill_script>
			<scheduler_pid_file_dir>scheduler pid file dir</scheduler_pid_file_dir>
		</agent_options>
		<transfer>
			<operation>copy</operation>
			<file_spec>.*</file_spec>
			<source>
				<host>host</host>
				<port>x22</port>
				<protocol>protocol</protocol>
				<user>user</user>
				<password>password</password>
				<ssh_auth_method>ssh_auth_method</ssh_auth_method>
				<ssh_auth_file>ssh_auth_file</ssh_auth_file>
			</source>
			<target>
				<host>host</host>
				<port>x22</port>
				<protocol>protocol</protocol>
				<user>user</user>
				<password>password</password>
				<ssh_auth_method>ssh_auth_method</ssh_auth_method>
				<ssh_auth_file>ssh_auth_file</ssh_auth_file>
			</target>
		</transfer>
		<ssh>
			<user>test</user>
			<password>myPwd</password>
			<sudo_password>mySudoPwd</sudo_password>
			<auth_method>password</auth_method>
			<port>x22</port>
		</ssh>
		<postprocessing>
			<command>echo ${ssh.sudo_password} | sudo cp ${install_path}/bin/jobscheduler_agent.sh /etc/init.d/jobscheduler</command>
			<command>echo ${ssh.sudo_password} | sudo update-rc.d jobscheduler defaults</command>
		</postprocessing>
	</installation>
</installations>
